
# database init, supports mysql too
database=oracle
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=SYSTEM
spring.datasource.password=Waybig
spring.datasource.driver.class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=none